const express=require('express')
const router=express.Router()
const auth=require('../controller/auth.controller')
const { accessAdmintoken } = require('../middleware/admin.middleware')
const {accesstoken} = require('../middleware/auth.middleware')
const { accessTeachertoken } = require('../middleware/Teacher.middleware')
const Image=require("../middleware/image.middleware")
router.post("/Login",auth.Login)
router.post("/Login/Admin",auth.LoginAdmin)
router.post("/Login/Teacher",auth.LoginTeacher)
router.post("/Resgiter",auth.Resgiter)
router.post("/Reset",accesstoken,auth.resetpassword)
router.post("/Refreshtoken",auth.refesthtoken)
router.post("/",auth.settoke)
router.post("/GetALL/",accessTeachertoken,auth.getALLHS)
router.post("/GetALL/GD/",auth.getALLGD)
router.post("/Search/HS",accessTeachertoken,auth.SearchHS)
router.put("/",accesstoken,Image.uploadImageuser,auth.update)
router.delete("/:username",accessAdmintoken,auth.deleteAuth)
router.post("/GET/users/LKK/",accesstoken,auth.getuserid)
module.exports=router