const express=require('express')
const router=express.Router()
const Class=require("../controller/class.controller")
const {accesstoken} = require('../middleware/auth.middleware')
const { accessTeachertoken } = require('../middleware/Teacher.middleware')
router.post("/",accessTeachertoken,Class.AddClass)
router.post("/getpage/",Class.getclassALL)
router.post("/Teacher/Getad/",accessTeachertoken,Class.GetClassTeacher)
router.get("/:tenlop",Class.searchclass)
router.get("/GetByID/:id",Class.GetIDClass)
router.post("/Search/Class/",Class.SearchClassTen)
router.put("/:id",accessTeachertoken,Class.updateclass)
router.delete("/:id",accessTeachertoken,Class.deleteclass)
module.exports=router